
export const authSagasActions = {
    FETCH_AUTH_LOGIN: 'FETCH_AUTH_LOGIN',
    FETCH_AUTH_SING_UP: 'FETCH_AUTH_SING_UP',
    SUCCESS_FETCH_AUTH: 'SUCCESS_FETCH_AUTH',
    ERROR_FETCH_AUTH: 'ERROR_FETCH_AUTH',
}