
export const taxSagasActions = {
  FETCH_TAXES: 'FETCH_TAXES',
  FETCH_SUBMISSION_FORM_FIELDS: 'FETCH_SUBMISSION_FORM_FIELDS',
  FETCH_SUBMISSIONS: 'FETCH_SUBMISSIONS',
  FETCH_SEND_SUBMISSION_FORM_FIELDS: 'FETCH_SEND_SUBMISSION_FORM_FIELDS',
  FETCH_EDIT_SUBMISSION_FORM_FIELDS: 'FETCH_EDIT_SUBMISSION_FORM_FIELDS',
  FETCH_DELETE_SUBMISSION: 'FETCH_DELETE_SUBMISSION',
  FETCH_SEND_SUBMISSION: 'FETCH_SEND_SUBMISSION',
}